/* File: _geldamodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Fri Apr 26 15:48:31 2019
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <setjmp.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_gelda_error;
static PyObject *_gelda_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef signed char signed_char;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef void(*cb_fdif_in___user__routines_typedef)(int *,double *,int *,double *,int *,double *,int *);
typedef void(*cb_adif_in___user__routines_typedef)(int *,double *,int *,double *,int *,int *,double *,int *);
typedef void(*cb_edif_in___user__routines_typedef)(int *,double *,int *,double *,int *,int *,double *,int *);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"_gelda.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");

#define pyobj_from_double1(v) (PyFloat_FromDouble(v))
#define pyobj_from_int1(v) (PyInt_FromLong(v))
#define GETSCALARFROMPYTUPLE(tuple,index,var,ctype,mess) {\
        if ((capi_tmp = PyTuple_GetItem((tuple),(index)))==NULL) goto capi_fail;\
        if (!(ctype ## _from_pyobj((var),capi_tmp,mess)))\
            goto capi_fail;\
    }

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define SWAP(a,b,t) {\
    t *c;\
    c = a;\
    a = b;\
    b = c;}

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(_gelda_error,errstring);\
        /*goto capi_fail;*/\
    } else 
/* New SciPy */
#define TRYPYARRAYTEMPLATECHAR case NPY_STRING: *(char *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATELONG case NPY_LONG: *(long *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATEOBJECT case NPY_OBJECT: PyArray_SETITEM(arr,PyArray_DATA(arr),pyobj_from_ ## ctype ## 1(*v)); break;

#define TRYPYARRAYTEMPLATE(ctype,typecode) \
        PyArrayObject *arr = NULL;\
        if (!obj) return -2;\
        if (!PyArray_Check(obj)) return -1;\
        if (!(arr=(PyArrayObject *)obj)) {fprintf(stderr,"TRYPYARRAYTEMPLATE:");PRINTPYOBJERR(obj);return 0;}\
        if (PyArray_DESCR(arr)->type==typecode)  {*(ctype *)(PyArray_DATA(arr))=*v; return 1;}\
        switch (PyArray_TYPE(arr)) {\
                case NPY_DOUBLE: *(double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_INT: *(int *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONG: *(long *)(PyArray_DATA(arr))=*v; break;\
                case NPY_FLOAT: *(float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CDOUBLE: *(double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CFLOAT: *(float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BOOL: *(npy_bool *)(PyArray_DATA(arr))=(*v!=0); break;\
                case NPY_UBYTE: *(unsigned char *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BYTE: *(signed char *)(PyArray_DATA(arr))=*v; break;\
                case NPY_SHORT: *(short *)(PyArray_DATA(arr))=*v; break;\
                case NPY_USHORT: *(npy_ushort *)(PyArray_DATA(arr))=*v; break;\
                case NPY_UINT: *(npy_uint *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONG: *(npy_ulong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGLONG: *(npy_longlong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONGLONG: *(npy_ulonglong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CLONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_OBJECT: PyArray_SETITEM(arr, PyArray_DATA(arr), pyobj_from_ ## ctype ## 1(*v)); break;\
        default: return -2;\
        };\
        return 1


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _gelda_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int try_pyarr_from_double(PyObject* obj,double* v) {
    TRYPYARRAYTEMPLATE(double,'d');
}

static int create_cb_arglist(PyObject* fun,PyTupleObject* xa,const int maxnofargs,const int nofoptargs,int *nofargs,PyTupleObject **args,const char *errmess) {
    PyObject *tmp = NULL;
    PyObject *tmp_fun = NULL;
    int tot,opt,ext,siz,i,di=0;
    CFUNCSMESS("create_cb_arglist\n");
    tot=opt=ext=siz=0;
    /* Get the total number of arguments */
    if (PyFunction_Check(fun))
        tmp_fun = fun;
    else {
        di = 1;
        if (PyObject_HasAttrString(fun,"im_func")) {
            tmp_fun = PyObject_GetAttrString(fun,"im_func");
        }
        else if (PyObject_HasAttrString(fun,"__call__")) {
            tmp = PyObject_GetAttrString(fun,"__call__");
            if (PyObject_HasAttrString(tmp,"im_func"))
                tmp_fun = PyObject_GetAttrString(tmp,"im_func");
            else {
                tmp_fun = fun; /* built-in function */
                tot = maxnofargs;
                if (xa != NULL)
                    tot += PyTuple_Size((PyObject *)xa);
            }
            Py_XDECREF(tmp);
        }
        else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                tot += PyTuple_Size((PyObject *)xa);
            tmp_fun = fun;
        }
        else if (F2PyCapsule_Check(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                ext = PyTuple_Size((PyObject *)xa);
            if(ext>0) {
                fprintf(stderr,"extra arguments tuple cannot be used with CObject call-back\n");
                goto capi_fail;
            }
            tmp_fun = fun;
        }
    }
if (tmp_fun==NULL) {
fprintf(stderr,"Call-back argument must be function|instance|instance.__call__|f2py-function but got %s.\n",(fun==NULL?"NULL":Py_TYPE(fun)->tp_name));
goto capi_fail;
}
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__code__")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount"))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_code")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"func_code"),"co_argcount"))
#endif
            tot = PyInt_AsLong(PyObject_GetAttrString(tmp,"co_argcount")) - di;
        Py_XDECREF(tmp);
    }
    /* Get the number of optional arguments */
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_defaults")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"func_defaults")))
#endif
            opt = PyTuple_Size(tmp);
        Py_XDECREF(tmp);
    }
    /* Get the number of extra arguments */
    if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
    /* Calculate the size of call-backs argument list */
    siz = MIN(maxnofargs+ext,tot);
    *nofargs = MAX(0,siz-ext);
#ifdef DEBUGCFUNCS
    fprintf(stderr,"debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),tot,opt,ext,siz,nofargs=%d(-%d),%d,%d,%d,%d,%d\n",maxnofargs,nofoptargs,tot,opt,ext,siz,*nofargs);
#endif
    if (siz<tot-opt) {
        fprintf(stderr,"create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=%d,%d,%d).\n",siz,tot,opt);
        goto capi_fail;
    }
    /* Initialize argument list */
    *args = (PyTupleObject *)PyTuple_New(siz);
    for (i=0;i<*nofargs;i++) {
        Py_INCREF(Py_None);
        PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
    }
    if (xa != NULL)
        for (i=(*nofargs);i<siz;i++) {
            tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
            Py_INCREF(tmp);
            PyTuple_SET_ITEM(*args,i,tmp);
        }
    CFUNCSMESS("create_cb_arglist-end\n");
    return 1;
capi_fail:
    if ((PyErr_Occurred())==NULL)
        PyErr_SetString(_gelda_error,errmess);
    return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _gelda_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(dgelda,DGELDA)(cb_edif_in___user__routines_typedef,cb_adif_in___user__routines_typedef,cb_fdif_in___user__routines_typedef,int*,double*,double*,double*,double*,int*,int*,double*,int*,int*,double*,int*,double*,double*,int*,int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/************************ cb_edif_in___user__routines ************************/
PyObject *cb_edif_in___user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_edif_in___user__routines_args_capi = NULL;
int cb_edif_in___user__routines_nofargs = 0;
jmp_buf cb_edif_in___user__routines_jmpbuf;
/*typedef void(*cb_edif_in___user__routines_typedef)(int *,double *,int *,double *,int *,int *,double *,int *);*/
static void cb_edif_in___user__routines (int *n_cb_capi,double *t_cb_capi,int *idif_cb_capi,double *e,int *lde_cb_capi,int *ipar,double *rpar,int *ierr_cb_capi) {
  PyTupleObject *capi_arglist = cb_edif_in___user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int n=(*n_cb_capi);
  double t=(*t_cb_capi);
  int idif=(*idif_cb_capi);
  int lde=(*lde_cb_capi);
  int ierr=(*ierr_cb_capi);
  npy_intp e_Dims[2] = {-1, -1};
  npy_intp ipar_Dims[1] = {-1};
  npy_intp rpar_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_edif_in___user__routines (maxnofargs=7(-2))\n");
  CFUNCSMESSPY("cb:cb_edif_in___user__routines_capi=",cb_edif_in___user__routines_capi);
  if (cb_edif_in___user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_edif_in___user__routines_capi = PyObject_GetAttrString(_gelda_module,"edif");
  }
  if (cb_edif_in___user__routines_capi==NULL) {
    PyErr_SetString(_gelda_error,"cb: Callback edif not defined (as an argument or module _gelda attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_edif_in___user__routines_capi)) {
  cb_edif_in___user__routines_typedef cb_edif_in___user__routines_cptr;
  cb_edif_in___user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_edif_in___user__routines_capi);
  (*cb_edif_in___user__routines_cptr)(n_cb_capi,t_cb_capi,idif_cb_capi,e,lde_cb_capi,ipar,rpar,ierr_cb_capi);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(_gelda_module,"edif_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(_gelda_error,"Failed to convert _gelda.edif_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(_gelda_error,"Callback edif argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  e_Dims[0]=lde,e_Dims[1]=n;
  ipar_Dims[0]=1;
  rpar_Dims[0]=1;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_edif_in___user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_double1(t)))
      goto capi_fail;
  if (cb_edif_in___user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(idif)))
      goto capi_fail;
  if (cb_edif_in___user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,2,e_Dims,NPY_DOUBLE,NULL,(char*)e,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_edif_in___user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_INT == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,ipar_Dims,NPY_INT,NULL,(char*)ipar,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_edif_in___user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,rpar_Dims,NPY_DOUBLE,NULL,(char*)rpar,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_edif_in___user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(n)))
      goto capi_fail;
  if (cb_edif_in___user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(lde)))
      goto capi_fail;
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function edif.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_edif_in___user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_edif_in___user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i)
    GETSCALARFROMPYTUPLE(capi_return,capi_i++,ierr_cb_capi,int,"int_from_pyobj failed in converting argument ierr of call-back function cb_edif_in___user__routines to C int\n");
  CFUNCSMESS("cb:cb_edif_in___user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_edif_in___user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_edif_in___user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/********************* end of cb_edif_in___user__routines *********************/


/************************ cb_adif_in___user__routines ************************/
PyObject *cb_adif_in___user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_adif_in___user__routines_args_capi = NULL;
int cb_adif_in___user__routines_nofargs = 0;
jmp_buf cb_adif_in___user__routines_jmpbuf;
/*typedef void(*cb_adif_in___user__routines_typedef)(int *,double *,int *,double *,int *,int *,double *,int *);*/
static void cb_adif_in___user__routines (int *n_cb_capi,double *t_cb_capi,int *idif_cb_capi,double *a,int *lda_cb_capi,int *ipar,double *rpar,int *ierr_cb_capi) {
  PyTupleObject *capi_arglist = cb_adif_in___user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int n=(*n_cb_capi);
  double t=(*t_cb_capi);
  int idif=(*idif_cb_capi);
  int lda=(*lda_cb_capi);
  int ierr=(*ierr_cb_capi);
  npy_intp a_Dims[2] = {-1, -1};
  npy_intp ipar_Dims[1] = {-1};
  npy_intp rpar_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_adif_in___user__routines (maxnofargs=7(-2))\n");
  CFUNCSMESSPY("cb:cb_adif_in___user__routines_capi=",cb_adif_in___user__routines_capi);
  if (cb_adif_in___user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_adif_in___user__routines_capi = PyObject_GetAttrString(_gelda_module,"adif");
  }
  if (cb_adif_in___user__routines_capi==NULL) {
    PyErr_SetString(_gelda_error,"cb: Callback adif not defined (as an argument or module _gelda attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_adif_in___user__routines_capi)) {
  cb_adif_in___user__routines_typedef cb_adif_in___user__routines_cptr;
  cb_adif_in___user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_adif_in___user__routines_capi);
  (*cb_adif_in___user__routines_cptr)(n_cb_capi,t_cb_capi,idif_cb_capi,a,lda_cb_capi,ipar,rpar,ierr_cb_capi);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(_gelda_module,"adif_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(_gelda_error,"Failed to convert _gelda.adif_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(_gelda_error,"Callback adif argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  a_Dims[0]=lda,a_Dims[1]=n;
  ipar_Dims[0]=1;
  rpar_Dims[0]=1;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_adif_in___user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_double1(t)))
      goto capi_fail;
  if (cb_adif_in___user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(idif)))
      goto capi_fail;
  if (cb_adif_in___user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,2,a_Dims,NPY_DOUBLE,NULL,(char*)a,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_adif_in___user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_INT == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,ipar_Dims,NPY_INT,NULL,(char*)ipar,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_adif_in___user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,rpar_Dims,NPY_DOUBLE,NULL,(char*)rpar,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_adif_in___user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(n)))
      goto capi_fail;
  if (cb_adif_in___user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(lda)))
      goto capi_fail;
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function adif.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_adif_in___user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_adif_in___user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i)
    GETSCALARFROMPYTUPLE(capi_return,capi_i++,ierr_cb_capi,int,"int_from_pyobj failed in converting argument ierr of call-back function cb_adif_in___user__routines to C int\n");
  CFUNCSMESS("cb:cb_adif_in___user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_adif_in___user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_adif_in___user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/********************* end of cb_adif_in___user__routines *********************/


/************************ cb_fdif_in___user__routines ************************/
PyObject *cb_fdif_in___user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_fdif_in___user__routines_args_capi = NULL;
int cb_fdif_in___user__routines_nofargs = 0;
jmp_buf cb_fdif_in___user__routines_jmpbuf;
/*typedef void(*cb_fdif_in___user__routines_typedef)(int *,double *,int *,double *,int *,double *,int *);*/
static void cb_fdif_in___user__routines (int *n_cb_capi,double *t_cb_capi,int *idif_cb_capi,double *f,int *ipar,double *rpar,int *ierr_cb_capi) {
  PyTupleObject *capi_arglist = cb_fdif_in___user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int n=(*n_cb_capi);
  double t=(*t_cb_capi);
  int idif=(*idif_cb_capi);
  int ierr=(*ierr_cb_capi);
  npy_intp f_Dims[1] = {-1};
  npy_intp ipar_Dims[1] = {-1};
  npy_intp rpar_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_fdif_in___user__routines (maxnofargs=6(-1))\n");
  CFUNCSMESSPY("cb:cb_fdif_in___user__routines_capi=",cb_fdif_in___user__routines_capi);
  if (cb_fdif_in___user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_fdif_in___user__routines_capi = PyObject_GetAttrString(_gelda_module,"fdif");
  }
  if (cb_fdif_in___user__routines_capi==NULL) {
    PyErr_SetString(_gelda_error,"cb: Callback fdif not defined (as an argument or module _gelda attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_fdif_in___user__routines_capi)) {
  cb_fdif_in___user__routines_typedef cb_fdif_in___user__routines_cptr;
  cb_fdif_in___user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_fdif_in___user__routines_capi);
  (*cb_fdif_in___user__routines_cptr)(n_cb_capi,t_cb_capi,idif_cb_capi,f,ipar,rpar,ierr_cb_capi);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(_gelda_module,"fdif_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(_gelda_error,"Failed to convert _gelda.fdif_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(_gelda_error,"Callback fdif argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  f_Dims[0]=n;
  ipar_Dims[0]=1;
  rpar_Dims[0]=1;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_fdif_in___user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_double1(t)))
      goto capi_fail;
  if (cb_fdif_in___user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(idif)))
      goto capi_fail;
  if (cb_fdif_in___user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,f_Dims,NPY_DOUBLE,NULL,(char*)f,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_fdif_in___user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_INT == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,ipar_Dims,NPY_INT,NULL,(char*)ipar,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_fdif_in___user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,rpar_Dims,NPY_DOUBLE,NULL,(char*)rpar,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_fdif_in___user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(n)))
      goto capi_fail;
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function fdif.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_fdif_in___user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_fdif_in___user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i)
    GETSCALARFROMPYTUPLE(capi_return,capi_i++,ierr_cb_capi,int,"int_from_pyobj failed in converting argument ierr of call-back function cb_fdif_in___user__routines to C int\n");
  CFUNCSMESS("cb:cb_fdif_in___user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_fdif_in___user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_fdif_in___user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/********************* end of cb_fdif_in___user__routines *********************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** dgelda ***********************************/
static char doc_f2py_rout__gelda_dgelda[] = "\
xprime,cval,iwarn,ierr = dgelda(edif,adif,fdif,t,tout,x,ipar,rpar,rtol,atol,[neq,method,info,edif_extra_args,adif_extra_args,fdif_extra_args])\n\nWrapper for ``dgelda``.\
\n\nParameters\n----------\n"
"edif : call-back function\n"
"adif : call-back function\n"
"fdif : call-back function\n"
"t : in/output rank-0 array(float,'d')\n"
"tout : input float\n"
"x : in/output rank-1 array('d') with bounds (neq)\n"
"ipar : input rank-1 array('i') with bounds (1)\n"
"rpar : input rank-1 array('d') with bounds (1)\n"
"rtol : input rank-1 array('d') with bounds (neq)\n"
"atol : input rank-1 array('d') with bounds (neq)\n"
"\nOther Parameters\n----------------\n"
"edif_extra_args : input tuple, optional\n    Default: ()\n"
"adif_extra_args : input tuple, optional\n    Default: ()\n"
"fdif_extra_args : input tuple, optional\n    Default: ()\n"
"neq : input int, optional\n    Default: len(x)\n"
"method : input int, optional\n    Default: 1\n"
"info : input rank-1 array('i') with bounds (20)\n"
"\nReturns\n-------\n"
"xprime : rank-1 array('d') with bounds (neq)\n"
"cval : rank-1 array('i') with bounds (4)\n"
"iwarn : int\n"
"ierr : int\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"  def edif(t,idif,e,ipar,rpar,[n,lde]): return ierr\n\
  Required arguments:\n"
"    t : input float\n"
"    idif : input int\n"
"    e : in/output rank-2 array('d') with bounds (lde,n)\n"
"    ipar : in/output rank-1 array('i') with bounds (1)\n"
"    rpar : in/output rank-1 array('d') with bounds (1)\n"
"  Optional arguments:\n"
"    n : input int, optional\n    Default: shape(e,1)\n"
"    lde : input int, optional\n    Default: shape(e,0)\n"
"  Return objects:\n"
"    ierr : int\n"
"  def adif(t,idif,a,ipar,rpar,[n,lda]): return ierr\n\
  Required arguments:\n"
"    t : input float\n"
"    idif : input int\n"
"    a : in/output rank-2 array('d') with bounds (lda,n)\n"
"    ipar : input rank-1 array('i') with bounds (1)\n"
"    rpar : input rank-1 array('d') with bounds (1)\n"
"  Optional arguments:\n"
"    n : input int, optional\n    Default: shape(a,1)\n"
"    lda : input int, optional\n    Default: shape(a,0)\n"
"  Return objects:\n"
"    ierr : int\n"
"  def fdif(t,idif,f,ipar,rpar,[n]): return ierr\n\
  Required arguments:\n"
"    t : input float\n"
"    idif : input int\n"
"    f : in/output rank-1 array('d') with bounds (n)\n"
"    ipar : input rank-1 array('i') with bounds (1)\n"
"    rpar : input rank-1 array('d') with bounds (1)\n"
"  Optional arguments:\n"
"    n : input int, optional\n    Default: len(f)\n"
"  Return objects:\n"
"    ierr : int";
/* extern void F_FUNC(dgelda,DGELDA)(cb_edif_in___user__routines_typedef,cb_adif_in___user__routines_typedef,cb_fdif_in___user__routines_typedef,int*,double*,double*,double*,double*,int*,int*,double*,int*,int*,double*,int*,double*,double*,int*,int*,int*,int*); */
static PyObject *f2py_rout__gelda_dgelda(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(cb_edif_in___user__routines_typedef,cb_adif_in___user__routines_typedef,cb_fdif_in___user__routines_typedef,int*,double*,double*,double*,double*,int*,int*,double*,int*,int*,double*,int*,double*,double*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  PyObject *edif_capi = Py_None;
  PyTupleObject *edif_xa_capi = NULL;
  PyTupleObject *edif_args_capi = NULL;
  int edif_nofargs_capi = 0;
  cb_edif_in___user__routines_typedef edif_cptr;
  PyObject *adif_capi = Py_None;
  PyTupleObject *adif_xa_capi = NULL;
  PyTupleObject *adif_args_capi = NULL;
  int adif_nofargs_capi = 0;
  cb_adif_in___user__routines_typedef adif_cptr;
  PyObject *fdif_capi = Py_None;
  PyTupleObject *fdif_xa_capi = NULL;
  PyTupleObject *fdif_args_capi = NULL;
  int fdif_nofargs_capi = 0;
  cb_fdif_in___user__routines_typedef fdif_cptr;
  int neq = 0;
  PyObject *neq_capi = Py_None;
  double t = 0;
  PyObject *t_capi = Py_None;
  double tout = 0;
  PyObject *tout_capi = Py_None;
  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double *xprime = NULL;
  npy_intp xprime_Dims[1] = {-1};
  const int xprime_Rank = 1;
  PyArrayObject *capi_xprime_tmp = NULL;
  int capi_xprime_intent = 0;
  int *cval = NULL;
  npy_intp cval_Dims[1] = {-1};
  const int cval_Rank = 1;
  PyArrayObject *capi_cval_tmp = NULL;
  int capi_cval_intent = 0;
  int *ipar = NULL;
  npy_intp ipar_Dims[1] = {-1};
  const int ipar_Rank = 1;
  PyArrayObject *capi_ipar_tmp = NULL;
  int capi_ipar_intent = 0;
  PyObject *ipar_capi = Py_None;
  double *rpar = NULL;
  npy_intp rpar_Dims[1] = {-1};
  const int rpar_Rank = 1;
  PyArrayObject *capi_rpar_tmp = NULL;
  int capi_rpar_intent = 0;
  PyObject *rpar_capi = Py_None;
  int *iwork = NULL;
  npy_intp iwork_Dims[1] = {-1};
  const int iwork_Rank = 1;
  PyArrayObject *capi_iwork_tmp = NULL;
  int capi_iwork_intent = 0;
  int liw = 0;
  double *rwork = NULL;
  npy_intp rwork_Dims[1] = {-1};
  const int rwork_Rank = 1;
  PyArrayObject *capi_rwork_tmp = NULL;
  int capi_rwork_intent = 0;
  int lrw = 0;
  double *rtol = NULL;
  npy_intp rtol_Dims[1] = {-1};
  const int rtol_Rank = 1;
  PyArrayObject *capi_rtol_tmp = NULL;
  int capi_rtol_intent = 0;
  PyObject *rtol_capi = Py_None;
  double *atol = NULL;
  npy_intp atol_Dims[1] = {-1};
  const int atol_Rank = 1;
  PyArrayObject *capi_atol_tmp = NULL;
  int capi_atol_intent = 0;
  PyObject *atol_capi = Py_None;
  int method = 0;
  PyObject *method_capi = Py_None;
  int *info = NULL;
  npy_intp info_Dims[1] = {-1};
  const int info_Rank = 1;
  PyArrayObject *capi_info_tmp = NULL;
  int capi_info_intent = 0;
  PyObject *info_capi = Py_None;
  int iwarn = 0;
  int ierr = 0;
  static char *capi_kwlist[] = {"edif","adif","fdif","t","tout","x","ipar","rpar","rtol","atol","neq","method","info","edif_extra_args","adif_extra_args","fdif_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOO|OOOO!O!O!:_gelda.dgelda",\
    capi_kwlist,&edif_capi,&adif_capi,&fdif_capi,&t_capi,&tout_capi,&x_capi,&ipar_capi,&rpar_capi,&rtol_capi,&atol_capi,&neq_capi,&method_capi,&info_capi,&PyTuple_Type,&edif_xa_capi,&PyTuple_Type,&adif_xa_capi,&PyTuple_Type,&fdif_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable edif */
if(F2PyCapsule_Check(edif_capi)) {
  edif_cptr = F2PyCapsule_AsVoidPtr(edif_capi);
} else {
  edif_cptr = cb_edif_in___user__routines;
}

  edif_nofargs_capi = cb_edif_in___user__routines_nofargs;
  if (create_cb_arglist(edif_capi,edif_xa_capi,7,2,&cb_edif_in___user__routines_nofargs,&edif_args_capi,"failed in processing argument list for call-back edif.")) {
    jmp_buf edif_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `edif`.\n");
    SWAP(edif_capi,cb_edif_in___user__routines_capi,PyObject);
    SWAP(edif_args_capi,cb_edif_in___user__routines_args_capi,PyTupleObject);
    memcpy(&edif_jmpbuf,&cb_edif_in___user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable adif */
if(F2PyCapsule_Check(adif_capi)) {
  adif_cptr = F2PyCapsule_AsVoidPtr(adif_capi);
} else {
  adif_cptr = cb_adif_in___user__routines;
}

  adif_nofargs_capi = cb_adif_in___user__routines_nofargs;
  if (create_cb_arglist(adif_capi,adif_xa_capi,7,2,&cb_adif_in___user__routines_nofargs,&adif_args_capi,"failed in processing argument list for call-back adif.")) {
    jmp_buf adif_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `adif`.\n");
    SWAP(adif_capi,cb_adif_in___user__routines_capi,PyObject);
    SWAP(adif_args_capi,cb_adif_in___user__routines_args_capi,PyTupleObject);
    memcpy(&adif_jmpbuf,&cb_adif_in___user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable fdif */
if(F2PyCapsule_Check(fdif_capi)) {
  fdif_cptr = F2PyCapsule_AsVoidPtr(fdif_capi);
} else {
  fdif_cptr = cb_fdif_in___user__routines;
}

  fdif_nofargs_capi = cb_fdif_in___user__routines_nofargs;
  if (create_cb_arglist(fdif_capi,fdif_xa_capi,6,1,&cb_fdif_in___user__routines_nofargs,&fdif_args_capi,"failed in processing argument list for call-back fdif.")) {
    jmp_buf fdif_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `fdif`.\n");
    SWAP(fdif_capi,cb_fdif_in___user__routines_capi,PyObject);
    SWAP(fdif_args_capi,cb_fdif_in___user__routines_args_capi,PyTupleObject);
    memcpy(&fdif_jmpbuf,&cb_fdif_in___user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable t */
    f2py_success = double_from_pyobj(&t,t_capi,"_gelda.dgelda() 4th argument (t) can't be converted to double");
  if (f2py_success) {
  /* Processing variable tout */
    f2py_success = double_from_pyobj(&tout,tout_capi,"_gelda.dgelda() 5th argument (tout) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x */
  ;
  capi_x_intent |= F2PY_INTENT_INOUT;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_gelda_error,"failed in converting 6th argument `x' of _gelda.dgelda to C/Fortran array" );
  } else {
    x = (double *)(PyArray_DATA(capi_x_tmp));

  /* Processing variable cval */
  cval_Dims[0]=4;
  capi_cval_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_cval_tmp = array_from_pyobj(NPY_INT,cval_Dims,cval_Rank,capi_cval_intent,Py_None);
  if (capi_cval_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_gelda_error,"failed in converting hidden `cval' of _gelda.dgelda to C/Fortran array" );
  } else {
    cval = (int *)(PyArray_DATA(capi_cval_tmp));

  /* Processing variable ipar */
  ipar_Dims[0]=1;
  capi_ipar_intent |= F2PY_INTENT_IN;
  capi_ipar_tmp = array_from_pyobj(NPY_INT,ipar_Dims,ipar_Rank,capi_ipar_intent,ipar_capi);
  if (capi_ipar_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_gelda_error,"failed in converting 7th argument `ipar' of _gelda.dgelda to C/Fortran array" );
  } else {
    ipar = (int *)(PyArray_DATA(capi_ipar_tmp));

  /* Processing variable rpar */
  rpar_Dims[0]=1;
  capi_rpar_intent |= F2PY_INTENT_IN;
  capi_rpar_tmp = array_from_pyobj(NPY_DOUBLE,rpar_Dims,rpar_Rank,capi_rpar_intent,rpar_capi);
  if (capi_rpar_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_gelda_error,"failed in converting 8th argument `rpar' of _gelda.dgelda to C/Fortran array" );
  } else {
    rpar = (double *)(PyArray_DATA(capi_rpar_tmp));

  /* Processing variable method */
  if (method_capi == Py_None) method = 1; else
    f2py_success = int_from_pyobj(&method,method_capi,"_gelda.dgelda() 2nd keyword (method) can't be converted to int");
  if (f2py_success) {
  /* Processing variable info */
  info_Dims[0]=20;
  capi_info_intent |= F2PY_INTENT_IN|F2PY_OPTIONAL;
  capi_info_tmp = array_from_pyobj(NPY_INT,info_Dims,info_Rank,capi_info_intent,info_capi);
  if (capi_info_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_gelda_error,"failed in converting 3rd keyword `info' of _gelda.dgelda to C/Fortran array" );
  } else {
    info = (int *)(PyArray_DATA(capi_info_tmp));

  /* Processing variable iwarn */
  /* Processing variable ierr */
  /* Processing variable neq */
  if (neq_capi == Py_None) neq = len(x); else
    f2py_success = int_from_pyobj(&neq,neq_capi,"_gelda.dgelda() 1st keyword (neq) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(x)>=neq,"len(x)>=neq","1st keyword neq","dgelda:neq=%d",neq) {
  /* Processing variable xprime */
  xprime_Dims[0]=neq;
  capi_xprime_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_xprime_tmp = array_from_pyobj(NPY_DOUBLE,xprime_Dims,xprime_Rank,capi_xprime_intent,Py_None);
  if (capi_xprime_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_gelda_error,"failed in converting hidden `xprime' of _gelda.dgelda to C/Fortran array" );
  } else {
    xprime = (double *)(PyArray_DATA(capi_xprime_tmp));

  /* Processing variable liw */
  liw = 20+6*neq;
  /* Processing variable lrw */
  lrw = 1000*neq*neq;
  /* Processing variable rtol */
  rtol_Dims[0]=neq;
  capi_rtol_intent |= F2PY_INTENT_IN;
  capi_rtol_tmp = array_from_pyobj(NPY_DOUBLE,rtol_Dims,rtol_Rank,capi_rtol_intent,rtol_capi);
  if (capi_rtol_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_gelda_error,"failed in converting 9th argument `rtol' of _gelda.dgelda to C/Fortran array" );
  } else {
    rtol = (double *)(PyArray_DATA(capi_rtol_tmp));

  /* Processing variable atol */
  atol_Dims[0]=neq;
  capi_atol_intent |= F2PY_INTENT_IN;
  capi_atol_tmp = array_from_pyobj(NPY_DOUBLE,atol_Dims,atol_Rank,capi_atol_intent,atol_capi);
  if (capi_atol_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_gelda_error,"failed in converting 10th argument `atol' of _gelda.dgelda to C/Fortran array" );
  } else {
    atol = (double *)(PyArray_DATA(capi_atol_tmp));

  /* Processing variable iwork */
  iwork_Dims[0]=liw;
  capi_iwork_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_CACHE;
  capi_iwork_tmp = array_from_pyobj(NPY_INT,iwork_Dims,iwork_Rank,capi_iwork_intent,Py_None);
  if (capi_iwork_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_gelda_error,"failed in converting hidden `iwork' of _gelda.dgelda to C/Fortran array" );
  } else {
    iwork = (int *)(PyArray_DATA(capi_iwork_tmp));

  /* Processing variable rwork */
  rwork_Dims[0]=lrw;
  capi_rwork_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_CACHE;
  capi_rwork_tmp = array_from_pyobj(NPY_DOUBLE,rwork_Dims,rwork_Rank,capi_rwork_intent,Py_None);
  if (capi_rwork_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_gelda_error,"failed in converting hidden `rwork' of _gelda.dgelda to C/Fortran array" );
  } else {
    rwork = (double *)(PyArray_DATA(capi_rwork_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_edif_in___user__routines_jmpbuf)) || (setjmp(cb_adif_in___user__routines_jmpbuf)) || (setjmp(cb_fdif_in___user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(edif_cptr,adif_cptr,fdif_cptr,&neq,&t,&tout,x,xprime,cval,ipar,rpar,iwork,&liw,rwork,&lrw,rtol,atol,&method,info,&iwarn,&ierr);
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  f2py_success = try_pyarr_from_double(t_capi,&t);
  if (f2py_success) {
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNii",capi_xprime_tmp,capi_cval_tmp,iwarn,ierr);
/*closepyobjfrom*/
  } /*if (f2py_success) of t pyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    Py_XDECREF(capi_rwork_tmp);
  }  /*if (capi_rwork_tmp == NULL) ... else of rwork*/
  /* End of cleaning variable rwork */
    Py_XDECREF(capi_iwork_tmp);
  }  /*if (capi_iwork_tmp == NULL) ... else of iwork*/
  /* End of cleaning variable iwork */
  if((PyObject *)capi_atol_tmp!=atol_capi) {
    Py_XDECREF(capi_atol_tmp); }
  }  /*if (capi_atol_tmp == NULL) ... else of atol*/
  /* End of cleaning variable atol */
  if((PyObject *)capi_rtol_tmp!=rtol_capi) {
    Py_XDECREF(capi_rtol_tmp); }
  }  /*if (capi_rtol_tmp == NULL) ... else of rtol*/
  /* End of cleaning variable rtol */
  /* End of cleaning variable lrw */
  /* End of cleaning variable liw */
  }  /*if (capi_xprime_tmp == NULL) ... else of xprime*/
  /* End of cleaning variable xprime */
  } /*CHECKSCALAR(len(x)>=neq)*/
  } /*if (f2py_success) of neq*/
  /* End of cleaning variable neq */
  /* End of cleaning variable ierr */
  /* End of cleaning variable iwarn */
  if((PyObject *)capi_info_tmp!=info_capi) {
    Py_XDECREF(capi_info_tmp); }
  }  /*if (capi_info_tmp == NULL) ... else of info*/
  /* End of cleaning variable info */
  } /*if (f2py_success) of method*/
  /* End of cleaning variable method */
  if((PyObject *)capi_rpar_tmp!=rpar_capi) {
    Py_XDECREF(capi_rpar_tmp); }
  }  /*if (capi_rpar_tmp == NULL) ... else of rpar*/
  /* End of cleaning variable rpar */
  if((PyObject *)capi_ipar_tmp!=ipar_capi) {
    Py_XDECREF(capi_ipar_tmp); }
  }  /*if (capi_ipar_tmp == NULL) ... else of ipar*/
  /* End of cleaning variable ipar */
  }  /*if (capi_cval_tmp == NULL) ... else of cval*/
  /* End of cleaning variable cval */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of tout*/
  /* End of cleaning variable tout */
  } /*if (f2py_success) of t*/
  /* End of cleaning variable t */
    CFUNCSMESS("Restoring jmpbuf for `fdif`.\n");
    cb_fdif_in___user__routines_capi = fdif_capi;
    Py_DECREF(cb_fdif_in___user__routines_args_capi);
    cb_fdif_in___user__routines_args_capi = fdif_args_capi;
    cb_fdif_in___user__routines_nofargs = fdif_nofargs_capi;
    memcpy(&cb_fdif_in___user__routines_jmpbuf,&fdif_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable fdif */
    CFUNCSMESS("Restoring jmpbuf for `adif`.\n");
    cb_adif_in___user__routines_capi = adif_capi;
    Py_DECREF(cb_adif_in___user__routines_args_capi);
    cb_adif_in___user__routines_args_capi = adif_args_capi;
    cb_adif_in___user__routines_nofargs = adif_nofargs_capi;
    memcpy(&cb_adif_in___user__routines_jmpbuf,&adif_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable adif */
    CFUNCSMESS("Restoring jmpbuf for `edif`.\n");
    cb_edif_in___user__routines_capi = edif_capi;
    Py_DECREF(cb_edif_in___user__routines_args_capi);
    cb_edif_in___user__routines_args_capi = edif_args_capi;
    cb_edif_in___user__routines_nofargs = edif_nofargs_capi;
    memcpy(&cb_edif_in___user__routines_jmpbuf,&edif_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable edif */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of dgelda *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"dgelda",-1,{{-1}},0,(char *)F_FUNC(dgelda,DGELDA),(f2py_init_func)f2py_rout__gelda_dgelda,doc_f2py_rout__gelda_dgelda},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "_gelda",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit__gelda(void) {
#else
#define RETVAL
PyMODINIT_FUNC init_gelda(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = _gelda_module = PyModule_Create(&moduledef);
#else
  m = _gelda_module = Py_InitModule("_gelda", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module _gelda (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module '_gelda' is auto-generated with f2py (version:2).\nFunctions:\n"
"  xprime,cval,iwarn,ierr = dgelda(edif,adif,fdif,t,tout,x,ipar,rpar,rtol,atol,neq=len(x),method=1,info=,edif_extra_args=(),adif_extra_args=(),fdif_extra_args=())\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  _gelda_error = PyErr_NewException ("_gelda.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"_gelda");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
